# Generated by Django 2.2 on 2019-12-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
        ('newsapp', '0003_news_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsHasTechnicalSolutions',
            new_name='NewsProduct',
        ),
    ]
