# Generated by Django 2.2 on 2019-12-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_auto_20191211_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsproduct',
            name='name',
        ),
        migrations.AlterField(
            model_name='newsdiscussitem',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsapp.News', verbose_name='новость обсуждения'),
        ),
    ]
