# Generated by Django 2.2 on 2019-12-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_auto_20191211_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('DELETED', 'DELETED'), ('FORMING', 'FORMING'), ('REDACTION', 'REDACTION'), ('READY', 'READY')], default='FORMING', max_length=20, verbose_name='статус'),
        ),
    ]
