# Generated by Django 2.2 on 2020-01-10 07:25

from django.db import migrations
import imagekit.models.fields
import newsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20191212_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='news_avatars/default_bridge.png', upload_to=newsapp.models.image_upload_to, verbose_name='картинка новости'),
        ),
    ]
