# Generated by Django 2.2 on 2019-12-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdiscussitem',
            name='comment',
            field=models.TextField(default=0, max_length=1500, verbose_name='добавить сообщение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdiscussitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projectsapp.Project', verbose_name='проект'),
        ),
        migrations.DeleteModel(
            name='ProjectDiscussMember',
        ),
    ]
