# Generated by Django 2.2 on 2020-01-10 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20200103_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagers',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
