# Generated by Django 2.2 on 2019-11-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_auto_20191107_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='text_for_map',
        ),
    ]
