# Generated by Django 2.2 on 2019-12-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0002_auto_20191221_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchapp.DocumentCategory', verbose_name='категория документа'),
        ),
    ]
