# Generated by Django 2.2 on 2019-12-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0008_auto_20191218_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='price',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='alt_materials',
            field=models.ManyToManyField(to='productsapp.Material', verbose_name='альтернативные материалы'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='productsapp.Material', verbose_name='Основной материал'),
        ),
    ]
