# Generated by Django 2.2 on 2019-12-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_auto_20191218_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='alt_materials',
            field=models.ManyToManyField(blank=True, to='productsapp.Material', verbose_name='альтернативные материалы'),
        ),
    ]
