# Generated by Django 2.2 on 2019-12-11 11:32

import authapp.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=authapp.models.image_upload_to, verbose_name='Аватар'),
        ),
    ]
